# Generated by Django 2.1 on 2020-05-02 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('storage_text', models.TextField(null=True, verbose_name='存证文本')),
                ('state', models.IntegerField(default=0, verbose_name='申请状态')),
                ('remark', models.CharField(max_length=255, verbose_name='备注')),
            ],
            options={
                'verbose_name': '公共字段',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('number', models.CharField(max_length=100, verbose_name='编号')),
                ('pwd', models.CharField(max_length=100, verbose_name='密码')),
                ('phoneNumber', models.CharField(max_length=100, null=True, verbose_name='手机号码')),
                ('sex', models.CharField(max_length=2, verbose_name='性别')),
                ('age', models.CharField(max_length=100, null=True, verbose_name='年龄')),
                ('college', models.CharField(max_length=100, null=True, verbose_name='学院')),
                ('major', models.CharField(max_length=100, null=True, verbose_name='专业')),
                ('sclass', models.CharField(max_length=100, null=True, verbose_name='班级')),
                ('type', models.IntegerField(default=1, verbose_name='用户类型')),
            ],
            options={
                'verbose_name': '公共字段',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storage',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.User', verbose_name='申请用户'),
        ),
    ]
