# Generated by Django 2.1 on 2020-05-02 23:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
