# Generated by Django 2.1 on 2020-05-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='approve_time',
            field=models.DateTimeField(null=True, verbose_name='审批时间'),
        ),
    ]
