# Generated by Django 2.1 on 2020-05-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_storage_approve_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='storage_img',
            field=models.FileField(null=True, upload_to='img', verbose_name='申请状态'),
        ),
    ]
