# Generated by Django 2.1 on 2020-05-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_storage_storage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='storage_img_name',
            field=models.CharField(max_length=255, null=True, verbose_name='图片名'),
        ),
    ]
