# Generated by Django 2.1 on 2020-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_storage_storage_img_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='user_name',
            field=models.CharField(default=1, max_length=255, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='user_number',
            field=models.CharField(default=1, max_length=255, verbose_name='学号'),
            preserve_default=False,
        ),
    ]
